# Generated by Django 5.1.6 on 2025-02-27 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={
                "ordering": ["views"],
                "verbose_name": "Пост",
                "verbose_name_plural": "Посты",
            },
        ),
        migrations.RenameField(
            model_name="post",
            old_name="is_publicated",
            new_name="is_published",
        ),
    ]
