# Generated by Django 5.1.6 on 2025-02-27 12:25

import django.utils.timezone
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите ваше имя и фамилию",
                        max_length=50,
                        verbose_name="Имя и Фамилия",
                    ),
                ),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        help_text="Введите описание категории",
                        max_length=128,
                        region=None,
                        unique=True,
                        verbose_name="Номер телефона",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        help_text="Введите ваше сообщение",
                        null=True,
                        verbose_name="Сообщение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Контакт",
                "verbose_name_plural": "Контакты",
                "ordering": ["phone", "name", "message"],
            },
        ),
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Введите описание категории",
                null=True,
                verbose_name="Описание категории",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Введите дату создания",
                verbose_name="Дата создания",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите фотографию продукта",
                null=True,
                upload_to="images/",
                verbose_name="Фотография",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0.0,
                help_text="Введите цену продукта",
                max_digits=100,
                verbose_name="Цена",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Введите дату изменения",
                verbose_name="Дата изменения",
            ),
        ),
    ]
